# Basic Site Settings
title: "Scholarn"
description: "The best educational website for students and teachers worldwide."
url: "https://scholarn.com"
baseurl: ""
lang: "en"
permalink: pretty

author:
  name: "Md Azaharuddin"
  email: "#@scholarn.com"

timezone: "Asia/Kolkata"

#theme: minima
minima:
  skin: "dark"

# Google Analytics
google_analytics: "G-63DKL6PLX8"

# Navigation Menu
header_pages:
  - about.md
  - contact.md
  - blog.md
  - courses.md
  - mock-test.md
  
# Set default
defaults:
  # Apply to all pages
  - scope:
      path: ""  # An empty string means all files in the project
    values:
      layout: "page"

  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"
      category: "blog"
      tags: ["learning", "courses"]
      
# Apply to all courses
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "page"
      tags: ["lms", "online learning"]

# Collections Settings
collections:
  courses:
    output: true
    permalink: /courses/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Generate social links in footer.
social_links:
  - { platform: github,         user_url: "https://github.com/scholarn" }
  
