# Basic Site Settings
title: "Scholarn"
description: "Online School To Learn From Anywhere"
url: "https://scholarn.com"
baseurl: ""
lang: "en"

author:
  name: "Md Azaharuddin"

timezone: "Asia/Kolkata"

theme: minima
minima:
  skin: "dark"

# Google Analytics
google_analytics: "G-63DKL6PLX8"

# Navigation Menu
header_pages:
  - about.md
  - contact.md
  - courses.md
  - mock-test.md
  - syllabus.md
  - previous-years-question-papers.md
  - typing-test.md
  
# Set default
defaults:
  # Apply to all pages
  - scope:
      path: ""  # An empty string means all files in the project
      types: "pages"
    values:
      layout: "page"
      
# Apply to all courses
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "page"

# Aplly to all lessons
  - scope:
      path: ""      
      type: "lessons"
    values:
      layout: "page"
      category: "grammar"
      author: "Md Azaharuddin"
      tags:
        - grammar
        - english
        - lessons
      keywords: "English grammar, grammar lesson, grammar rules, English language"

# Aplly to all syllabus
  - scope:
      path: ""
      type: "syllabus"
    values:
      layout: "page"
    
  # Apply to all mocktest
  - scope:
      path: ""
      type: "mocktests"
    values:
      layout: "mocktest"

# Collections Settings
collections:
  courses:
    output: true
    permalink: /courses/:title/

  lessons:
    output: true
    permalink: /courses/english-grammar/:title/

  mocktests:
    output: true
    permalink: /mock-test/:title/

  syllabus:
    output: true
    permalink: /syllabus/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty  
exclude:
  - '*.gemspec'
