# Basic Site Settings
title: "Scholarn"
description: "A School to Learn Together."
url: "https://scholarn.com"
baseurl: ""
lang: "en"
permalink: pretty

author:
  name: "Md Azaharuddin"

timezone: "Asia/Kolkata"

theme: minima
minima:
  skin: "dark"

# Google Analytics
google_analytics: "G-63DKL6PLX8"

# Navigation Menu
header_pages:
  - about.md
  - contact.md
  - blog.md
  - courses.md
  - mock-test.md
  
# Set default
defaults:
  - scope:
      path: "blog.md"
    values:
      layout: "home"
  # Apply to all pages
  - scope:
      path: ""  # An empty string means all files in the project
      types: "pages"
    values:
      layout: "page"

  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"
      author: "Md Azaharuddin"
      
# Apply to all courses
  - scope:
      type: "courses"
    values:
      layout: "page"

# Aplly to all lessons
  - scope:
      type: "lessons"
    values:
      layout: "post"
      category: "grammar"
      author: "Md Azaharuddin"
      tags:
        - grammar
        - english
        - lessons
      keywords: "English grammar, grammar lesson, grammar rules, English language"

# Collections Settings
collections:
  courses:
    output: true
    permalink: /courses/:title/

  lessons:
    output: true
    permalink: /courses/english-grammar/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
