# Basic Site Settings
title: "Scholarn"
description: "The best educational website for students and teachers worldwide."
url: "https://scholarn.com"
baseurl: ""
lang: "en"
permalink: pretty

author:
  name: "Md Azaharuddin"

timezone: "Asia/Kolkata"

remote_theme: jekyll/minima
minima:
  skin: "dark"

# Google Analytics
google_analytics: "G-63DKL6PLX8"

# Navigation Menu
header_pages:
  - about.md
  - contact.md
  - courses.md
  - mock-test.md
  
# Set default
defaults:
  # Apply to all pages
  - scope:
      path: ""  # An empty string means all files in the project
      types: "pages"
    values:
      layout: "page"

  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"
      
# Apply to all courses
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "page"

# Collections Settings
collections:
  courses:
    output: true
    permalink: /courses/:path/

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

